### ISSUE TITLE
Embedding 4: Dataset RLS missing details

### ISSUE THREAD

**Issue by darien2020** [sigmacomputing/sigmaquickstarts#35]
Step: Dataset RLS 
1. Between renaming the new copy of the dataset and adding a new column we need to instruct the user to click on the Worksheet tab of the new dataset and ensure that they are in Edit mode. 
2. After adding the new filter on ua_Region we need to explain that it is ok if they don't see data here. After this step we also need to Publish the new dataset. 
3. Provide instruction on how to rename a WB page. 
4. What does "adding" the new dataset to a new Workbook page mean? Create a new table element off of this dataset? 
5. In my RLS server.js the "ua_Region" param is commented out and the value is set to "East,West"
6. Missing set of steps for updating path, secret, client-id, account_type, userTeam etc. for the new (RLS) server.js 
7. Worth noting the syntax for the user attribute param, as this gives you trouble if your UA is not specifically called "Region", to include searchParams += `&:ua_${attribute_name}=${attribute_value}`
8. Sending 2 comma separated values via embed UA param requires a step for updating the formula in the underlying Sigma RLS Dataset for the ua_Region column. The equality formula needs to be replaced with a Contains(), for ex: Contains(CurrentUserAttributeText("Darien_Region"), [Store Region])

**Comment by pballai** [comment]
1: Between renaming the new copy of the dataset and adding a new column we need to instruct the user to click on the Worksheet tab of the new dataset and ensure that they are in Edit mode.
PB - Fixed

2: After adding the new filter on ua_Region we need to explain that it is ok if they don't see data here. After this step we also need to Publish the new dataset.
PB - Fixed

3: Provide instruction on how to rename a WB page.
PB - Each QS in the Embedding series assumes user has either done the previous QSs or already understands the basics (if the just did one in the series). Therefore we believe user understands some workflow tasks.

4: What does "adding" the new dataset to a new Workbook page mean? Create a new table element off of this dataset?
PB - Fixed

5: In my RLS server.js the "ua_Region" param is commented out and the value is set to "East,West"
PB - This is intentional to show the syntax when passing multiple values, and lets user just comment one line in favor of the other when doing the single value vs. multiple.

6: Missing set of steps for updating path, secret, client-id, account_type, userTeam etc. for the new (RLS) server.js
PB - same answer as #3

4: Worth noting the syntax for the user attribute param, as this gives you trouble if your UA is not specifically called "Region", to include searchParams += &:ua_${attribute_name}=${attribute_value}
PB - Added inline note

5: Sending 2 comma separated values via embed UA param requires a step for updating the formula in the underlying Sigma RLS Dataset for the ua_Region column. The equality formula needs to be replaced with a Contains(), for ex: Contains(CurrentUserAttributeText("Darien_Region"), [Store Region])
PB - Fixed

6: Actions and Events QS: on page 5 Actions using URL we refer to sigma-embed_actions_url folder
PB - Fixed
